name: fan2dev
description: "Flutter App Empty Template for Android, iOS, Web and Windows. This template is a starting point for a Flutter application."
publish_to: "none"

version: 1.1.0+5

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_localized_locales: ^2.0.5
  go_router: ^12.1.1
  intl: ^0.18.1
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  retrofit: ^4.0.3
  dio: ^5.4.0
  cloud_firestore: ^4.13.6
  flutter_animate: ^4.5.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.4
  firebase_storage: ^11.6.0
  cached_network_image: ^3.3.1
  sentry_flutter: ^7.19.0
  talker_flutter: ^4.2.4
  talker_dio_logger: ^4.2.4
  talker_bloc_logger: ^4.2.4
  talker: ^4.2.4
  animated_toast_list: ^1.0.2
  flutter_markdown: ^0.7.2
  colorful_safe_area: ^1.0.0
  auto_size_text: ^3.0.0
  gif: ^2.3.0
  firebase_messaging: ^14.9.4
  share_plus: ^9.0.0
  file_saver: ^0.2.13

dev_dependencies:
  bloc_test: ^9.1.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  husky: ^0.1.6
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  retrofit_generator: ^8.0.6

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/images/projects/entropia_erp/
    - assets/images/projects/we_cancer_survivors/
    - assets/images/projects/dream_diary/
    - assets/images/blog/
    - assets/images/blog/categories/
    - assets/icons/
    - assets/icons/technologies/
    - assets/texts/
    - assets/animations/
