// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA39J8GkGZW3S-eEJONB99t5qaM5bc2WbY',
    appId: '1:901872844965:web:36895277eb55b0663d8d4c',
    messagingSenderId: '901872844965',
    projectId: 'fan2dev-personal-app',
    authDomain: 'fan2dev-personal-app.firebaseapp.com',
    storageBucket: 'fan2dev-personal-app.appspot.com',
    measurementId: 'G-8QY8Q52MGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCllNC1pLhX6e8jUpX5uVQmO8Lw3fp8IuM',
    appId: '1:901872844965:android:26ec4b71bf6ccbc13d8d4c',
    messagingSenderId: '901872844965',
    projectId: 'fan2dev-personal-app',
    storageBucket: 'fan2dev-personal-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7DBSPXFdSjPoWk1ophonNa7tAhZy7iU0',
    appId: '1:901872844965:ios:0ae0c772ccb7b5933d8d4c',
    messagingSenderId: '901872844965',
    projectId: 'fan2dev-personal-app',
    storageBucket: 'fan2dev-personal-app.appspot.com',
    iosBundleId: 'me.fan2dev.app.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7DBSPXFdSjPoWk1ophonNa7tAhZy7iU0',
    appId: '1:901872844965:ios:4227027c8d2752693d8d4c',
    messagingSenderId: '901872844965',
    projectId: 'fan2dev-personal-app',
    storageBucket: 'fan2dev-personal-app.appspot.com',
    iosBundleId: 'com.example.flutterAppEmptyTemplate.RunnerTests',
  );
}
